### ISSUE TITLE
Gulp-babel dependency version mismatch

### ISSUE THREAD

**Issue by zewa666** [aurelia/skeleton-plugin#1]
The Skeleton as well as other repos reference gulp babel like this:

 "gulp-babel": "^5.0.0",

maybe we should keep that synced.

**Comment by EisenbergEffect** [comment]
@zewa666 What is your recommendation for that?

**Comment by zewa666** [comment]
I'd just recommend setting it back to the same as the skelly. Created a PR for that.

**Comment by EisenbergEffect** [comment]
Closing this as it will get fixed as part of the next release.
