### ISSUE TITLE
This repository needs "refreshment"

### ISSUE THREAD

**Issue by adriatic** [aurelia/skeleton-plugin#11]
By refreshment I think the addition of the "Feature Plugins" as introduced [here](http://aurelia.io/docs.html#plugins) is required. In addition, I would really like to see the addition of the sample code (no need to drag the whole [Navigation Skeleton(https://github.com/aurelia/skeleton-navigation) to show the use of this plugin. Without such sample this feels like half of the "total".

**Comment by EisenbergEffect** [comment]
I'm not following you entirely. This is a repo for someone who wants to make a plugin, not use one. Can you clarify more?

**Comment by adriatic** [comment]
Well, you need to drop **your** level of understanding of Aurelia Plugin concept to the **average novice** to Aurelia programming model (a service I am trying to provide here :-) ). Since I am working on the Aurelia-Guides, I noted a lot of confusion about what plugins are, and then both how to create and subsequently use them; the assumed case where one person creates a plugin and a completely different one consumes it is less often present with the introduction `Feature Plugins`:

> The above plugin API is designed to enable the installation of external, 3rd party plugins. However, you may wish to organize your own project as a series of plugins. To do this, simply create a folder for your internal "feature" plugin. In that folder create an index.js file that exports a single configure function. This function works the same as 3rd party plugins. To register your feature for configuration at startup, you would use the following code:
> 
> ``` javascript
> aurelia.use.plugin('plugin-name', config => { /* configuration work */ });
> ```

I would indeed be even little more specific and show something like:

``` javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .plugin('hello world');  // install the plugin

  aurelia.start().then(a => a.setRoot());
}
```

and then finish with a few sentences explaining where to put the generated plugin      files (say E6 version)

![image](https://cloud.githubusercontent.com/assets/2712405/9806226/1a2d9f10-5810-11e5-8003-2232bc639561.png)

so that the project that consumes this plugin.

This last part is important because of all commotion related to "relative paths" / "absolute paths" issues that jspm recently caused

Making sense?

**Note** that I could not decide off the top off my head whether the plugin name should be `hello world` or `hello-world` or something else since these naming conventions (camel case, pascal, introduction of the `dash` between words are not always intuitive

**Comment by EisenbergEffect** [comment]
This repo has nothing to do with "feature" though. This is a starter kit for people who want to create a 3rd party plugin that does not exist inside your project but that is installed into your app via jspm.

**Comment by adriatic** [comment]
Understood and agreed seeing your comment - particularly the **that is installed into your app via jspm**, a fact that completely escaped me until now. 

**Important** - the following text was written with the intent to learn from you (or whoever might be your delegate) how does this stuff work. I posted twice these same questions in Gitter chat room and only learned that even some "prominent" names do not know how to answer my questions. If the answer I need already exists somewhere in the current documentation, please point me to it and I will then write a tutorial on Aurelia plugins that will remove the need to answer these elementary questions.

---

So, I went ahead and wrote a small Aurelia app that would use this plugin. The first problem was to find out what is this plugin name (to be used in the typical `main.js` class of the client. Based on the plugin file names:

![image](https://cloud.githubusercontent.com/assets/2712405/9833551/cc7dd438-5968-11e5-9e95-f4cbcfc46aca.png)

I concluded that the `main.js` should be written as

``` javascript
export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .plugin('hello-world');

  aurelia.start().then(a => a.setRoot());
}
```

When I run this app (`gulp serve`), I get this on Chrome console

```
DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-resources@0.15.2.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/history-browser@0.8.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/history-browser@0.8.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.16.1.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.16.1.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin http://localhost:9000/jspm_packages/github/aurelia/event-aggregator@0.8.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Configured plugin http://localhost:9000/jspm_packages/github/aurelia/event-aggregator@0.8.0.
aurelia-logging-console.js:38 DEBUG [aurelia] Loading plugin hello-world.
system.src.js:3987 GET http://localhost:9000/hello-world.js 404 (Not Found)M @ system.src.js:3987(anonymous function) @ system.src.js:3987b @ shim.min.js:1526o.fetch @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987(anonymous function) @ system.src.js:3987f @ shim.min.js:1415(anonymous function) @ shim.min.js:1423b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
shim.min.js:1444 Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:9000/hello-world.js(…)(anonymous function) @ shim.min.js:1444b.exports @ shim.min.js:453b.(anonymous function) @ shim.min.js:1625f @ shim.min.js:1596q @ shim.min.js:1600
```

I do not understand the meaning of  **`GET http://localhost:9000/hello-world.js 404 (Not Found)`** in this context. My understanding is that I managed to present the plugin name to the loader correctly (`main.js`), so it ought to be that this **"local name" is not properly related to it's "external" name that was given to jspm** - see the package.json file below

```
{
  "jspm": {
    "directories": {},
    "dependencies": {
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.17.0",
      "aurelia-framework": "github:aurelia/framework@^0.16.0",
      "aurelia/skeleton-plugin": "github:aurelia/skeleton-plugin@^0.3.0"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.6.4",
      "babel-runtime": "npm:babel-runtime@^5.6.4",
      "core-js": "npm:core-js@^0.9.4"
    },
    "overrides": {
      "npm:core-js@0.9.18": {
        "main": "client/shim.min"
      }
    }
  },
  "devDependencies": {
    "browser-sync": "^2.8.2",
    "gulp": "^3.9.0"
  },
  "overrides": {
    "npm:core-js@0.9.18": {
      "main": "client/shim.min"
    }
  }
}

```

**Comment by adriatic** [comment]
I have resolved all of my issues in this thread (nearly all of were my typos) and learned enough through chasing the solutions for these issues that I am now able to write a very detailed tutorial on plugins for Aurelia-Guides site. Please feel free to close this thread

**Comment by chips5k** [comment]
This is slightly related i guess... Any chance we can get this repo updated to match the skeleton nav repo's dependencies and the karma setup + gulp tasks?.

**Comment by chips5k** [comment]
Update - i am working on a PR for this, will submit very soon.

**Comment by gheoan** [comment]
I think this can be closed.
