### ISSUE TITLE
Add "sample" directory to plugin skeleton.

### ISSUE THREAD

**Issue by jwahyoung** [aurelia/skeleton-plugin#14]
This may bloat the project a bit, but I and some others have created a plugin configuration that adds a sample directory to the project structure for direct testing purposes. (This avoids the JSPM link workflow and generally simplifies things.) Having an included demo and test project has a real benefit for plugin authors.

The configuration is generic enough that it can (and should) be reused.

Of note, this feature is active in the ui-virtualization repo. I think it would be a boon to have it here.

**Comment by EisenbergEffect** [comment]
Git won't persist an empty directly. I think we can consider this recommendation for the docs on writing plugins though.

**Comment by cottrellio** [comment]
This feature would be so awesome to have. @eisenbergeffect I don't think he's talking about an empty directory, but if he was, you can add a `.gitkeep` file to the dir. Ember addons include a dummy app for development/ demo purposes and it's extremely helpful! @jedd-ahyoung do you still have this somewhere? I'd love to see it!
