### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by vegarringdal** [aurelia/skeleton-plugin#16]
Whats the best way to add css also?

Im doing this in a app to load element and css... and it works

``` javacsript
import 'bootstrap';


export function configure(aurelia) {
  aurelia.use
    .standardConfiguration()
    .developmentLogging()
    .globalResources('simpleGrid/simple-grids', "simpleGrid/simpleGrid.css");

  aurelia.start().then(a => a.setRoot());
}
```

Is this a very bad way of doing it btw?

This is what I would like to build into a plugin when Ive gotten it better.
https://github.com/vegarringdal/aureliaGrid

**Comment by EisenbergEffect** [comment]
That's not going to be the best way to load the css. It will work, but it would be better to require the css in your html for the component that uses it.

**Comment by vegarringdal** [comment]
made a new one..
