### ISSUE TITLE
Add typescript kit

### ISSUE THREAD

**Issue by lgabeskiria** [aurelia/skeleton-plugin#20]

**Comment by doktordirk** [comment]
working on it sortof. have added it to the spoonx plugins. so i have quite the good idea now on howto for community plugins

**Comment by EisenbergEffect** [comment]
We'll be adding support to the CLI for creating plugins.

**Comment by EisenbergEffect** [comment]
Issue moved to [aurelia/cli #215](https://github.com/aurelia/cli/issues/215) via [**ZenHub**](https://www.zenhub.com/)

**Comment by vegarringdal** [comment]
Ive stared on here too:
https://github.com/vegarringdal/skeleton-plugin-typescript

Also added a sample folder (no experts on gulp/typescript)

Im using it in my grid rebuild:
https://github.com/vegarringdal/vGrid
