### ISSUE TITLE
Webpack version

### ISSUE THREAD

**Issue by wshayes** [aurelia/skeleton-plugin#27]
Is there going to be a webpack version of the skeleton-plugin?

**Comment by EisenbergEffect** [comment]
There could be, but I'm wondering if we need to just somehow make it agnostic to both webpack and jspm. Since, the plugin itself should work with either tool, should we remove the tool dependencies from the plugin skeleton?

**Comment by EisenbergEffect** [comment]
Although, a solid plugin should be authored with both jspm and npm dependencies so it works in both places, so maybe it makes sense to leave it as is?

**Comment by EisenbergEffect** [comment]
Closing this since we are tracking a new issue for the CLI to enable creating plugin projects.

**Comment by cleytonb** [comment]
Hi,

I would also like to see an example using webpack. I haven't found the option to create a plugin using aurelia CLI.
