### ISSUE TITLE
package.json at odds

### ISSUE THREAD

**Issue by AdamWillden** [aurelia/skeleton-plugin#28]
I'm just learning about what should go into these package.json files (aside from the obvious) and I've noticed this.

CommonJS index main:
https://github.com/aurelia/skeleton-plugin/blob/master/package.json#L16

AMD index main:
https://github.com/aurelia/skeleton-plugin/blob/master/package.json#L60

Default JSPM format is cjs (CommonJS):
https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#format

Not sure it's really an issue, just wondering if they all should be CommonJS or if there's a reason JSPM is being set to AMD.

**Comment by EisenbergEffect** [comment]
JSPM can handle any format so it's not an issue really. We have some other tooling for require.js that is based on jspm config and I think that assumes an amd format. Really, it shouldn't matter though.

**Comment by AdamWillden** [comment]
No problem. Just pointing it out in case there was any reason to address it. Thanks.
