### ISSUE TITLE
plugin use own dependencies

### ISSUE THREAD

**Issue by dbrezoev** [aurelia/skeleton-plugin#30]
Hi, I know this is not an issue, but I thought here is the right place to ask this question, after some tryings in the gitter channel. 
So I make a plugin which uses moment js as dependency. But when I installed this plugin it wants moment to be installed in the global project. How can I say to my plugin when I "import moment from 'moment'" I need to load it from its own dependencies. I asked this question also here: 
http://patrickwalters.net/making-out-first-plugin/ 
Thanks in advance

**Comment by EisenbergEffect** [comment]
Answered elsewhere.
