### ISSUE TITLE
HTML Being parsed as Javascript

### ISSUE THREAD

**Issue by warent** [aurelia/skeleton-plugin#31]
I'm trying to make a plugin using this skeleton-plugin, and every time it says `Unexpected token <` when I run it like normal... If I change my template.html to something like `var test=true` then it doesn't throw that error. How come my html file is being parsed as a javascript file?

Full code here: https://github.com/VYNYL/aurelia-masonry

just do the typical `npm install` then `gulp serve` to see it happen.

Thank you for your assistance

**Comment by EisenbergEffect** [comment]
The best way to test a plugin is to have a separate "app" project that you test that plugin in, installing it the same way the consumer would. Otherwise, you're probably going to encounter all sorts of jspm/system.js configuration issues.
